import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { RightLayout } from "@/components/layouts/right/Right";
import { LeftLayout } from "@/components/layouts/left/Left";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="flex min-h-screen w-full ">
          <LeftLayout />
          <div className="relative flex flex-col min-w-0 mx-auto w-full max-w-[580px] lg:max-w-none lg:w-auto lg:aspect-[9/16] lg:h-screen ">
            {children}
          </div>
          <RightLayout />
        </main>
      </body>
    </html>
  );
}
